version: '3.8'
services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "cd /app && npm install && npm run dev"
    ports:
      - "4000:4000"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "cd /app && npm install && npm run dev"
    ports:
      - "3000:3000"